### ISSUE TITLE
Code not showing 

### ISSUE THREAD

**Issue by rufatkiu** [codewithrodi/Lovelace#2]
When GPT typing codes, there are nothing showed. Also this is the best gpt repo I seen, go team

**Comment by codewithrodi** [comment]
Hello @rufatkiu, a big apology in advance for the delay in responding to the reported error. I was interacting with Ada, and sure enough, there was the error you mention, **it was an error within the React application, because the data that was requested through the API was not being displayed or stored correctly**. It was solved, the commit was made with the changes made.

![Screenshot from 2023-10-09 01 16 01](https://github.com/codewithrodi/Lovelace/assets/69746956/acb4155d-9978-4740-a53f-a7bd319b22b0)

Also, thanks you very much for the comment you made `"Also, this is the best gpt repository I have ever seen, come on team"`, it motivates me to continue doing this!

Greetings @rufatkiu, from Chile, Talca.

**Comment by rufatkiu** [comment]
> Hello @rufatkiu, a big apology in advance for the delay in responding to the reported error. I was interacting with Ada, and sure enough, there was the error you mention, **it was an error within the React application, because the data that was requested through the API was not being displayed or stored correctly**. It was solved, the commit was made with the changes made.
> 
> ![Screenshot from 2023-10-09 01 16 01](https://user-images.githubusercontent.com/69746956/273497761-acb4155d-9978-4740-a53f-a7bd319b22b0.png)
> 
> Also, thanks you very much for the comment you made `"Also, this is the best gpt repository I have ever seen, come on team"`, it motivates me to continue doing this!
> 
> Greetings @rufatkiu, from Chile, Talca.

Greetings from China, Kunming City
